//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace merge_EIP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class messageBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public messageBoard()
        {
            this.watchCount = new HashSet<watchCount>();
        }
    
        public int messageboardNumber { get; set; }
        public string employeeID { get; set; }
        public string employeeName { get; set; }
        public System.DateTime messageDate { get; set; }
        public string messageText { get; set; }
        public string State { get; set; }
        public string assignPerson { get; set; }
        public string assignDepartment { get; set; }
        public bool goTop { get; set; }
        public bool toCalendar { get; set; }
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-ddThh:mm}",ApplyFormatInEditMode =true)]
        public Nullable<System.DateTime> toMsgDate { get; set; }
        public string messageTitle { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<watchCount> watchCount { get; set; }
    }
}
