//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace merge_EIP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class punchIn
    {
        [DataType(DataType.Date)]
        public System.DateTime punchinDate { get; set; }

        public string employeeID { get; set; }
        public Nullable<System.TimeSpan> clockIn { get; set; }
        public Nullable<System.TimeSpan> clockOut { get; set; }
        public string State { get; set; }
        public Nullable<decimal> bodyTemperature { get; set; }
        public Nullable<System.TimeSpan> startoverTime { get; set; }
        public Nullable<System.TimeSpan> endoverTime { get; set; }
        public Nullable<decimal> overtimeHours { get; set; }
        public Nullable<decimal> totalHours { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
