//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace merge_EIP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrder()
        {
            this.tOrderDetail = new HashSet<tOrderDetail>();
        }

        [Display(Name = "訂單編號")]
        public int fOrderId { get; set; }
        [Display(Name = "員工編號")]
        public string employeeID { get; set; }
        [Display(Name = "商店編號")]
        public int fStoreID { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "開始日期")]
        public System.DateTime fStartDate { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "結束日期")]
        public Nullable<System.DateTime> fEndDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        [Display(Name = "開始時間")]
        public System.TimeSpan fStartTime { get; set; }

        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        [Display(Name = "結束時間")]
        public System.TimeSpan fEndTime { get; set; }

        [Display(Name = "類型")]
        public string fType { get; set; }
        [Display(Name = "狀態")]
        public string fStatus { get; set; }

        // tShop資料表要接收的值
        [Display(Name = "店家")]
        public string fNewStore { get; set; }

        [Display(Name = "上傳菜單")]
        public string fImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        // 星期
        public string fWeek { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual tShop tShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderDetail> tOrderDetail { get; set; }
    }
}
